services:
  - type: web
    name: simple-python-server
    env: python
    plan: free
    buildCommand: "pip install -v requirements.txt"
    startCommand: "python index.py"
    envVars:
      - key: PORT
        value: 443
